### ISSUE TITLE
Add `.noop` alias prefix for `.deploy noop`

### ISSUE THREAD

**Issue by gleeblezoid** [github/branch-deploy#108]
> Capturing this in an issue before I fork off and start work on this.

At the moment we use branch-deploy a lot and it's slightly terrifying how easy it is to almost run a prod deploy when the intention is to run a noop deploy. 

It'd be very cool (in my opinion) to have the option of typing a very differently patterned command to reduce the margin for human error (especially with so many folks using that repo).

**Comment by tgharold** [comment]
> At the moment we use branch-deploy a lot and it's slightly terrifying how easy it is to almost run a prod deploy when the intention is to run a noop deploy.

This is especially true when used for IaC like Terraform deploys.  The default should be "plan" and not "apply".  Or to go further, allow "`.plan (env)`" and "`.apply (env)`" aliases to be configured somehow.

**Comment by GrantBirki** [comment]
I think the best solution here would be to have `noop_trigger` as a completely different keyword, rather than a subset of the `trigger` keyword.

For example:

> current code does this

```yaml
trigger: .deploy
noop_trigger: .noop
```

> current code interprets this as

```text
.deploy
.deploy .noop
```

That ^ is just silly. We want something like this:

> future

```yaml
trigger: .deploy
noop_trigger: .noop
```

> current code interprets this as

```text
.deploy
.noop
```

That was the noop command is no longer a suffix of `.deploy` and it is it's own standalone command.

**Comment by hashtagchris** [comment]
👋🏼 Long-time branch-deploy user. If I set `noop_trigger` to `.plan`, and a coworker overlooks the change and types the `.deploy noop <environment>`, will it be interpreted the same as before? Or safely error out?

**Comment by GrantBirki** [comment]
@hashtagchris it should safely error out as `.deploy noop <env>` will not be correctly parsed anymore. The `noop` text in your command will try to be parsed as an environment, see that it is not one, and fail.
