### ISSUE TITLE
Include branch SHA in outputs

### ISSUE THREAD

**Issue by KevinMSampson** [github/branch-deploy#115]
To ensure we're using the latest branch commit during the deployment step, we need the `sha` of the `ref` in the action's outputs as well. Very similar to how the ref is updated to use the specific sha for forks, but simply a separate output to use.

https://github.com/github/branch-deploy/blob/c2a6b34cdfdd0ddd7c73895e8ca6ffda6d45623e/src/functions/prechecks.js#LL144C5-L144C27

This will help when we branch-deploy back-to-back from a PR so we can check that we're deploying the right version without having to always run extra GitHub API calls to get the sha from the context's head.

_(this is my first real public issue requesting a feature - my apologies if I'm not doing this right_

**Comment by GrantBirki** [comment]
We _just_ published a release about an hour ago that might fix your exact needs

https://github.com/github/branch-deploy/releases/tag/v4.5.2

https://github.com/github/branch-deploy/pull/114

I would checkout those links and see if the new `sha` output will work for you

**Comment by GrantBirki** [comment]
new release published that properly supports this 🚀 

https://github.com/github/branch-deploy/releases/tag/v4.6.0
