### ISSUE TITLE
`update_branch: warn` doesn’t catch before createDeployment

### ISSUE THREAD

**Issue by KevinMSampson** [github/branch-deploy#122]
### Describe the Issue

When using the default for `update_branch` the expected warn and fail scenario is not run.

### Action Configuration

```
##[group]Run github/branch-deploy@v4.6.0
with:
  production_environment: prod
  environment_targets: sandbox,qa,prod
  environment: sandbox
  skip_completing: true
  github_token: ***
  status: success
  reaction: eyes
  trigger: .deploy
  noop_trigger: noop
  lock_trigger: .lock
  unlock_trigger: .unlock
  help_trigger: .help
  lock_info_alias: .wcid
  stable_branch: main
  prefix_only: true
  update_branch: warn
  required_contexts: false
  allow_forks: true
  admins: false
  admins_pat: false
  merge_deploy_mode: false
##[endgroup]
```

### Relevant Actions Log Output

```
Skipping commit status check and proceeding...
##[debug]raw graphql result for debugging:
##[debug]{"repository":{"pullRequest":{"reviewDecision":null,"mergeStateStatus":"HAS_HOOKS","commits":{"nodes":[{"commit":{"checkSuites":{"totalCount":1},"statusCheckRollup":null}}]}}}}
##[debug]raw admins value: false
##[debug]***** is not an admin
##[debug]precheck values for debugging:
##[debug]reviewDecision: null
##[debug]mergeStateStatus: HAS_HOOKS
##[debug]commitStatus: null
##[debug]userIsAdmin: false
##[debug]update_branch: warn
##[debug]skipCi: false
##[debug]skipReviews: false
##[debug]allowForks: true
##[debug]forkBypass: false
##[debug]environment: sandbox
##[debug]behind: false
⚠️ CI checks have not been defined and required reviewers have not been defined... proceeding - OK
```

### Extra Information

Using GHES 3.6.2 and including the log output that seems the most different from a GitHub Cloud run.

**Comment by GrantBirki** [comment]
@KevinMSampson if you try the same flow on `v4.6.1` do you get the same results?

**Comment by KevinMSampson** [comment]
> if you try the same flow on `v4.6.1` do you get the same results?

@GrantBirki yes.

#### Debug Notes

From what I can tell, this is what mainly differs:

```
Your test run values --- my test run values

# This might be a different issue but I'm not recognized as an admin, maybe because we only assign Teams not Users (best practice)
raw admins value: grantbirki --- false
GrantBirki is an admin via handle reference --- *** is not an admin

# Is HAS_HOOKS considered to be "behind"?
mergeStateStatus: BLOCKED --- HAS_HOOKS

# behind value is wrong
behind: true --- false
```

#### Probable cause

Current [`behind`](https://github.com/github/branch-deploy/blob/719af08838917ee8a8bdb8d63968df355b6cc17c/src/functions/prechecks.js#L259-L286) check logic only checks [MergeStateStatus](https://docs.github.com/en/enterprise-server@3.6/graphql/reference/enums#mergestatestatus) for `BLOCKED` and `BEHIND` values but we're getting `HAS_HOOKS`, since we use pre-receive hooks, leaving it set to false by default.

#### Suggestion

What do you think about updating this logic to account for some of the other values that also refer to mergeable code that may also indicate it's behind?

### Misc
As for the update introduced in `4.6.1`, I tested with `update_branch: disabled` and it work as expected!! The createDeployment call doesn't auto-sync the branch with a new, non-ci-triggering commit with a warning message, and continues with a successful message!

**Comment by GrantBirki** [comment]
@KevinMSampson I'm very excited to see that `v4.6.1` solved the issue for you with `update_branch: disabled`! As for the other issue of `HAS_HOOKS` I'm not entirely sure what to do about that. Taking a look at the docs, it appears that `HAS_HOOKS` is considered to be a "mergable" state

```text
HAS_HOOKS

Mergeable with passing commit status and pre-receive hooks.
```

> [source](https://docs.github.com/en/enterprise-server@3.6/graphql/reference/enums#mergestatestatus)

From your output though, I'm assuming by this line

    ```
    ⚠️ CI checks have not been defined and required reviewers have not been defined... proceeding - OK
    ```

that the workflow just carried right on and merged the branch because `update_branch` wasn't set to `disabled`. I think this warrants an explicit override option to strongly prevent against the updating of branches (particularly for your use case). Thoughts?

**Comment by KevinMSampson** [comment]
@GrantBirki It looks like that [`BLOCKED`](https://github.com/github/branch-deploy/blob/719af08838917ee8a8bdb8d63968df355b6cc17c/src/functions/prechecks.js#L262) conditional check does a comparison that should properly evaluate whether it's behind or not - could it be updated to run the same check for the other statuses as well?

Something like:
```
if (mergeStateStatus === 'BLOCKED') {

Updated to:

if (mergeStateStatus === 'BLOCKED' || mergeStateStatus === 'HAS_HOOKS') {
```

**Comment by GrantBirki** [comment]
That sounds like a fine solution to me! I'll draft up a fix

**Comment by GrantBirki** [comment]
This is now apart of [`v5.0.0`](https://github.com/github/branch-deploy/releases/tag/v5.0.0) which is a pre-release but should be made the latest release by the end of this week. It is now usable though

**Comment by KevinMSampson** [comment]
Thank you!!
