### ISSUE TITLE
Feature request: Allow specifying environment URL for deployments

### ISSUE THREAD

**Issue by jumoel** [github/branch-deploy#127]
Hey :wave:

It would be awesome if it was possible to pass in `environment_url` to Octokit, as https://octokit.github.io/rest.js/v19#repos-create-deployment-status specifies 🙂

**Comment by GrantBirki** [comment]
@jumoel This feature is now available in the pre-release version [`v5.1.0`](https://github.com/github/branch-deploy/releases/tag/v5.1.0)
