### ISSUE TITLE
Input option for `post_completing`

### ISSUE THREAD

**Issue by KevinMSampson** [github/branch-deploy#154]
### Details

Anyone using reusable workflows is almost always going to have multiple jobs, the first with the `github/branch-deploy` action using `skip_completing: true`, and the reusable workflow(s) as the rest.

I have multiple repos using branch-deploy and fear it will become a bit of a hassle managing updating the post-deploy job steps (as shown in a few examples using the `skip_completing` feature), especially as more features start coming out for the branch-deploy action.

### Request  

Similar to how the `skip_completing` input will skip select steps towards the end of the job, could there be a `post_completing` input that skips select steps at the beginning and runs the final update logic?

This way I know my first and last jobs will work as-expected and don't have to approve and maintain multiple 3rd party actions or custom `actions/github-script` action scripts

**Comment by GrantBirki** [comment]
👋 Hello again! I think I somewhat understand what you are asking for here but extra details could help as I'm still a bit confused.

> `post_completing` input that skips select steps at the beginning and runs the final update logic?

Could you elaborate on this a bit as well?

It might also help to have some pseudo-code of what you are doing currently, why it isn't working well, and a "mock" example of how you would like to see it implemented instead. If I can wrap my head around what you are trying to do and _why_, I can get into writing up some code to make this a reality. Thanks! ❤️

**Comment by GrantBirki** [comment]
@KevinMSampson I'm doing some tidying up and I'm going to go ahead and close this issue out. If you would like to revisit this, please feel free to re-open the issue and we can pick this back up. Thanks!
