### ISSUE TITLE
Multiple `production_environment`

### ISSUE THREAD

**Issue by mnaser** [github/branch-deploy#208]
### Describe the Issue

I've got a scenario where I have multiple production environments all managed in the same environment.

There doesn't seem to be a way to have multiple production environments managed within the same repository?  While there are ways to have multiple environments, it feels that the `production_environment` is meant for the main one?

Does it make sense to just set `production_environment` to something obscure if you have multiple production environments?

**Comment by GrantBirki** [comment]
@mnaser have you read the little bitsof docs that float around about this variable [here](https://github.com/github/branch-deploy/blob/bfd31c18fc52455450c33c0b3553509c6505ea60/action.yml#L36-L39)?

This variable effectively is just used to tell the GitHub API when a deployment starts if it is the "production" env or not.

You can read more about this variable in the [official GitHub docs](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#create-a-deployment) as well (see screenshot)

<img width="601" alt="Screenshot 2023-09-15 at 7 30 15 AM" src="https://github.com/github/branch-deploy/assets/23362539/6e4f95c1-b41e-4e2e-b76b-790289ddf811">

The majority of the use cases I have seen for this value is when users have a unique env name and they need to overwrite it. For example, if you call `production` something else like `prd`, or `prod` then you would want to use this variable.

That being said, I have actually not come across this use case that is yours yet. Please do some tinkering, swap around this variable, set it to something obscure, etc. Let me know the results here and how it works for you! If it doesn't work out well, I'll look into creating a solution. Thanks! 🙇

**Comment by mnaser** [comment]
@GrantBirki thanks!! i'm playing around with it, I actually do not have a single "production" environment in this case, so I left it set to `production` and trying to play with it on how it will end up working.

So far, so good, I haven't seen anything wild, the only thing is that  if someone does `.deploy` with no target, it will deploy try to `production` and inevitably fail because that 'environment' doesn't exist... i think the nice thing I'm thinking about would be if there's a way to have a bool that says "enforce_env" or something like that, so users MUST have an environment in their `.deploy` command

**Comment by GrantBirki** [comment]
@mnaser Would you be able to copy / paste or link to your branch-deploy configuration? I'm curious about what settings you have.

**Comment by GrantBirki** [comment]
I think the solution here is to have `production_environment` become `production_environments` (with an s). Then this value would accept a comma separated list of strings -> `beep,boop`. The branch-deploy Action would then mark `beep` and `boop` as production environments when making deployment requests.

This would fix the problem at hand for you and likely all other users in the future.

The only issue is that this would be a pretty significant breaking change as the input variable would change values by adding that trailing "s". However, I think we can show deprecation messages in the logs and push a `v8.0.0` tag.

**Comment by GrantBirki** [comment]
@mnaser Please go ahead and give the pre-release tag [`v8.0.0`](https://github.com/github/branch-deploy/releases/tag/v8.0.0) a go and let me know how it works! :rocket:

**Comment by mnaser** [comment]
@GrantBirki worked beautifully, thank you.
