### ISSUE TITLE
Ability to disable "naked" `.deploy`

### ISSUE THREAD

**Issue by mnaser** [github/branch-deploy#210]
### Describe the Issue

At the moment, there's no way of actually disabling the ability to run a naked `.deploy` and enforcing that the user _must_ specify the environment they are deploying to (aka `.deploy to foo`)

It's not particularily high priority, but it would be nice to have to improve UX.  Thank you for your work on this action.

**Comment by GrantBirki** [comment]
@mnaser This is now implemented in pre-release [`v8.1.0`](https://github.com/github/branch-deploy/releases/tag/v8.1.0). Test it out and let me know what you think! 🎉
