### ISSUE TITLE
Support deploying a specific SHA or branch

### ISSUE THREAD

**Issue by tiagonbotelho** [github/branch-deploy#211]
Hello 👋 

As part of being able to quickly revert a change to a specific point in time we were wondering if it'd be possible for the `branch-deploy` action to support deploying a specific SHA or `branch-name` to a given environment.

Something like `.deploy SHA to production` or `.deploy <my-fav-branch> to production` would be what I had in mind 😊 

Thanks!

**Comment by GrantBirki** [comment]
I'll work on implementing this feature

`.deploy [sha|tag|branch] to <environment>` should be supported

**Comment by GrantBirki** [comment]
@tiagonbotelho This is now implemented in pre-release [`v8.1.0`](https://github.com/github/branch-deploy/releases/tag/v8.1.0). Test it out and let me know what you think! 🎉
