### ISSUE TITLE
Checking if files have changed in PR branch deploy

### ISSUE THREAD

**Issue by hansarh** [github/branch-deploy#219]
### Details

I'm trying to use this [changed-files](https://github.com/tj-actions/changed-files) action to decide whether or not to run some subsequent steps. 
I've tried passing in the output sha of branch deploy to the action, but since the changed files task doesn't see the PR context it only checks for changes against the previous commit sha on the PR branch which isn't sufficient. Optimally I would like for it to check against the base sha of the branch or similar to PR context behaviour:
![image](https://github.com/github/branch-deploy/assets/6917956/7259b06d-c3fe-43a4-af6c-10081e1e010f)

Any input to how I can achieve this?

**Comment by GrantBirki** [comment]
:wave: @hansarh

This question might be better suited for that other project. I am unfamiliar with that Action or how to properly provide inputs from this Action into it to get your desired behavior.

It should be noted that the `github/branch-deploy` Action is considered an IssueOps workflow and the only supported context which this Action can run via `.deploy` commands is listed below:

```yaml
# The workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]
```

This might be an issue as it looks like the other Action you are trying to use wants `pull_request` event contexts. You will have to verify with the maintainers / community of that Action.

Good luck!

**Comment by hansarh** [comment]
You have outputs for git ref which you show examples of handling the checkout action to correctly check out PR branch. So I feel this action needs to support adjusting other actions to understand the trigger is actually a PR context.
This action supports `sha` and `base_sha` inputs. The sha output of this action works fine, but I'm unable to provide a base sha as of now. Can the base_ref output of this action be used and translated to a base_sha?
