### ISSUE TITLE
Include deployment started comment id in output

### ISSUE THREAD

**Issue by walkerk1980** [github/branch-deploy#312]
### Details

It would be useful to include this comment id in outputs.
https://github.com/github/branch-deploy/blob/368e17cf44738ebe4ee145839973967ceaf4ae44/src/main.js#L551-L568

This would allow the comment to be replaced with deployment results later in workflows, to reduce the number of comments on PR when using `skip_completing: true`.

In our workflows that use the `command` action where our own in progress comments are created, replacing the "in progress/deployment started" comment with the deployment results has made the Issue/PR comments much easier to follow.

```javascript
            // update in_progress_comment with the new content
            const in_progress_comment_id = process.env.in_progress_comment_id
            console.log('in_progress_comment_id: ' + in_progress_comment_id)
            if (in_progress_comment_id) {
              console.log('Updating in_progress comment with new content')
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: in_progress_comment_id,
                body: body
              })
            }
```

**Comment by GrantBirki** [comment]
Release tag [`v9.9.0`](https://github.com/github/branch-deploy/releases/tag/v9.9.0) published and I also updated the general `v9` tag to include these new changes. Thanks for your contribution @walkerk1980! 🎉
