### ISSUE TITLE
Introduce a `.help` command

### ISSUE THREAD

**Issue by tiagonbotelho** [github/branch-deploy#67]
We currently developed a small workflow that triggers whenever a PR get created providing instructions on how to use `branch-deploy`, like the image below.

<img width="1048" alt="Screenshot 2022-10-24 at 15 02 10" src="https://user-images.githubusercontent.com/9062611/197544506-09ae785f-e874-4ac3-9143-a2f521efc122.png">

It'd be great to introduce something similar to this by default in the action itself 🚀

**Comment by GrantBirki** [comment]
I think that is a great idea! From a user's perspective, would you rather have a native comment on the pull request or a link to the Action's [detailed usage guide](https://github.com/github/branch-deploy/blob/main/docs/usage.md)?

Or perhaps the `.help`  command outputs text that the workflow creator drafts up so it can display the exact text they want. Thoughts?

**Comment by tiagonbotelho** [comment]
@GrantBirki it is more a matter of personal preference, but to me having the `.help` output in my "working directory" (i.e. PR) would make the most sense. Since the action already has the metadata needed (environment, available environments, etc) maybe it can automatically generate a helpful `.help` message with a few examples by default? If the user wanted to extend that output maybe the action could enable that as well, but I personally don't see it as a must have 😛
