### ISSUE TITLE
Export locking functions

### ISSUE THREAD

**Issue by hfaulds** [github/branch-deploy#68]
I'm using `branch-deploy` but also want to be able to trigger individual deploys using workflow-dispatch. In order to do this I need to be able to control the locks myself rather than relying on `branch-deploy`.

I wonder if it would make sense to create an `actions` subdirectory for these two bits of functionality so we can reference them like this:
```
  uses: github/branch-deploy/actions/lock@vX.X.X
```

So then it'd be a case of writing our actions manifest and a little bit of javascript for the two actions:
- [ ] create `actions/lock/actions.yaml` and `actions/lock/index.js`
- [ ] create `actions/unlock/actions.yaml` and `actions/unlock/index.js`

WDYT?

**Comment by GrantBirki** [comment]
I **love** this idea! ❤️ 

I was struggling to think of an optimal way to have more flexible control over deploy locks. If we just had a standalone Action that claimed locks and could be invoked by other workflows, then that would be a great feature!

My availability is a little wonky over the next month or so but this is absolutely something I am interested in creating

**Comment by GrantBirki** [comment]
Also, this feature request could potentially remove the need for https://github.com/github/branch-deploy/pull/64

**Comment by GrantBirki** [comment]
Done! 🎉 

I opted for a completely standalone Action rather than messing with the source code of this repo

https://github.com/GrantBirki/lock

I will eventually transfer ^ the Action above to the GitHub Org
