### ISSUE TITLE
Code Coverage Badge

### ISSUE THREAD

**Issue by ppeters0502** [github/branch-deploy#72]
Any specific reason why the code coverage badge on the README.md is just an SVG? I just thought that seemed a little goofy, I mean I guess we always have 100% code coverage then? 😃

**Comment by GrantBirki** [comment]
Hey @ppeters0502! I do have an answer for ya 😄 

So it is a dynamically generated SVG.

If you look at the [code here](https://github.com/github/branch-deploy/blob/43afd75c657a06c55c953cc7af493d9cf565aa43/package.json#L12) that runs the test suite it generates a SVG that contains the percentage of code coverage for the repo. It should indeed *always* be at 100% as that is the requirement for this project. However, if it ever drops that drop will be reflected and committed so users are aware.

Hope that helps!
